# This is the network config written by 'subiquity'
network:
  ethernets:
    ens160:
      dhcp4: no
      addresses:
              - 10.0.5.90/24
      gateway4: 10.0.5.2
      nameservers:
          search: [emily.local]
          addresses: [10.0.5.5]
  version: 2
  renderer: networkd
